version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Jetty >= 10 requires JDK 11
      - dependency-name: "org.eclipse.jetty:jetty-server"
        versions:
          - ">= 10.0.0"
      - dependency-name: "org.eclipse.jetty:jetty-servlet"
        versions:
          - ">= 10.0.0"
      - dependency-name: "jersey.version"
        versions:
          - ">= 3"
    open-pull-requests-limit: 50
